# Generated by Django 3.1.2 on 2020-10-08 13:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(null=True, upload_to=app.models.user_directory_path, validators=[app.models.validate_file], verbose_name=''),
        ),
    ]
