# Generated by Django 3.1.2 on 2020-10-08 13:20

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201008_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(null=True, upload_to='files/<django.db.models.query_utils.DeferredAttribute object at 0x04329070>/', validators=[app.models.validate_file], verbose_name=''),
        ),
    ]
