# Generated by Django 3.1.2 on 2020-10-08 14:10

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201008_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='Helaro', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(null=True, upload_to='Media/%y/%m/%d/', validators=[app.models.validate_file, app.models.validate_file_size], verbose_name=''),
        ),
    ]
